name: mcnc-probe
include:
  - ./portainer/compose.yml
  - ./homepage/compose.yml
  - ./netdata/compose.yml
  - ./cacti/compose.yml
  - ./smokeping/compose.yml
  - ./speedtest/compose.yml
  - ./uptime-kuma/compose.yml
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.0/28
