version: '3'
services:
  speedtest:
    image: "mcncclovett/speedtest"
    container_name: "speedtest"
    restart: "unless-stopped"
    network_mode: "host"
    healthcheck:
      start_period: 30s
      timeout: 3s
      interval: 30s
      test: "curl -f http://localhost:80 || exit 1"
    labels:
      - homepage.group=Testing
      - homepage.name=Speedtest
      - homepage.icon=si-speedtest
      - homepage.href=http://${PROBE}/
      - homepage.description=Docker container management
