version: '3'
services:
  speedtest:
    image: "mcncclovett/speedtest"
    container_name: "speedtest"
    restart: "unless-stopped"
    network_mode: "host"
    healthcheck:
      start_period: 30s
      timeout: 3s
      interval: 30s
      test: "curl -f http://localhost:80 || exit 1"
