version: '3'
services:
  smokeping:
    image: "linuxserver/smokeping"
    container_name: smokeping
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - TZ=America/New_York
    volumes:
      - smokeping-data:/data
      - smokeping-config:/config
    healthcheck:
      start_period: 30s
      timeout: 3s
      interval: 30s
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/80' || exit 1"
    networks:
      smokeping:
volumes:
  smokeping-data:
  smokeping-config:
networks:
  smokeping:
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.8/29
