version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    labels:
      - homepage.group=Management
      - homepage.name=Portainer
      - homepage.icon=si-portainer
      - homepage.href=https://${PROBE}:9443/
      - homepage.description=Docker container management
volumes:
  portainer-data:
