version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer

volumes:
  portainer_data:
networks:
  portainer:
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.0/29
