version: '2'
services:
  uptime-kuma:
    image: "louislam/uptime-kuma:latest"
    container_name: uptime-kuma
    restart: unless-stopped
    stop_grace_period: 20s
    ports:
      - "3000:3001"
    environment:
      - TZ=America/New_York
    volumes:
      - uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      uptime-kuma:
volumes:
  uptime-kuma:
networks:
  uptime-kuma:
    ipam:
      driver: default
      config:
        - subnet: 203.0.113.16/29
