---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

theme: dark

color: neutral

#showStats: true

hideVersion: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
